### PR TITLE
Bump up SC to 3.11.0 version

### PR DESCRIPTION
**Pull request by willbasky**

### CODE REVIEW

**Comment by secretrow** [comment]
Hi,

Could you update this so it installs the latest 3.12.0 version? 

Many thanks for this great script.

**Comment by willbasky** [comment]
Hi! Thanks. @secretrow
I moved to mangaro where latest packages are available. So i can't check would it script work if i bump it up. I can renew and if you can test it locally and let me know it works, then I will try. Deal?

**Comment by secretrow** [comment]
Sounds good, thank you very much!

**Comment by willbasky** [comment]
@secretrow updated
Could you pull branch [3.12.0](https://github.com/willbasky/build-supercollider/tree/3.12.0) and test it build well?

**Pull request merged**
